---
# Single node
  - hosts: 192.168.33.10  
    become: yes
    become_user: root
    roles:
      - role: ../roles/opendistro/opendistro-elasticsearch
      - role: ../roles/wazuh/ansible-wazuh-manager
      - role: ../roles/wazuh/ansible-filebeat-oss
      - role: ../roles/opendistro/opendistro-kibana
    vars:
      single_node: true
      minimum_master_nodes: 1
      elasticsearch_node_master: true
      elasticsearch_network_host: 192.168.33.10
      filebeat_node_name: node-1
      filebeat_output_elasticsearch_hosts: 192.168.33.10
      instances:
        node1:
          name: node-1       # Important: must be equal to elasticsearch_node_name.
          ip: 192.168.33.10
      ansible_shell_allow_world_readable_temp: true
