---
# Prompt user for IP ADDRESS at run time
# And install all the components for Wazuh SOC against the provided IP ADDRESS
- vars_prompt:
  - name: es_ip_address
    prompt: " Please Enter Elasticsearch Host IP"
    private: no    

  hosts: "{{ es_ip_address }}"
  roles:
    - {role: ../roles/wazuh/ansible-wazuh-manager}
    - role: ../roles/wazuh/ansible-filebeat
      filebeat_output_elasticsearch_hosts: localhost:9200
    - {role: ../roles/elastic-stack/ansible-elasticsearch, elasticsearch_network_host: '0.0.0.0', single_node: true}
    - { role: ../roles/elastic-stack/ansible-kibana, elasticsearch_network_host: '0.0.0.0', elasticsearch_reachable_host: 'localhost' }
